blank_issues_enabled: true
contact_links:
  - name: ğŸ™ Question or Help
    url: https://github.com/beyond-all-reason/rfcs/discussions/new
    about: If you have a question or need help, ask a question on the discussion forums.
